controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
function SpawnBad (num: number, mySprite: Sprite) {
    for (let index = 0; index < num; index++) {
        let Level = 0
        let list: Image[] = []
        bad = sprites.create(list._pickRandom(), SpriteKind.Player)
        tiles.placeOnRandomTile(bad, sprites.skillmap.islandTile4)
        bad.setVelocity(50, 50)
        pause(100)
        if (Level > 5) {
            mySprite = sprites.create(img`
                ........................
                ........................
                ........................
                ........................
                ..........fffff.........
                ........ff1111bff.......
                .......fb1111111bf......
                .......f111111111f......
                ......fd1111111ffff.....
                ......fd111dd1c111bf....
                ......fb11fcdf1b1bff....
                ......f11111bfbfbff.....
                ......f1b1bdfcffff......
                ......fbfbfcfcccf.......
                ......ffffffffff........
                .........ffffff.........
                .........ffffff.........
                .........fffffff..f.....
                ..........fffffffff.....
                ...........fffffff......
                ........................
                ........................
                ........................
                ........................
                `, SpriteKind.Player)
            mySprite.setVelocity(50, 50)
            for (let index = 0; index < 4; index++) {
                tiles.placeOnRandomTile(mySprite, sprites.skillmap.islandTile4)
            }
        }
    }
}
let mySprite: Sprite = null
let bad: Sprite = null
bad = sprites.create(img`
    . . f f f . . . . . . . . f f f 
    . f f c c . . . . . . f c b b c 
    f f c c . . . . . . f c b b c . 
    f c f c . . . . . . f b c c c . 
    f f f c c . c c . f c b b c c . 
    f f c 3 c c 3 c c f b c b b c . 
    f f b 3 b c 3 b c f b c c b c . 
    . c b b b b b b c b b c c c . . 
    . c 1 b b b 1 b b c c c c . . . 
    c b b b b b b b b b c c . . . . 
    c b c b b b c b b b b f . . . . 
    f b 1 f f f 1 b b b b f c . . . 
    f b b b b b b b b b b f c c . . 
    . f b b b b b b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `, SpriteKind.Enemy)
tiles.setCurrentTilemap(tilemap`level1`)
let statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.setColor(6, 2)
statusbar.setLabel("HP")
statusbar.positionDirection(CollisionDirection.Top)
statusbar.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
tiles.placeOnTile(bad, tiles.getTileLocation(15, 0))
